name: "Delete Training Log"
description: "Remove an existing training log by date"
title: "Delete Training Log"
labels: ["delete-training-log"]
body:
  - type: dropdown
    id: dates
    attributes:
      label: "Select log dates to delete"
      description: "Choose one or more dates"
      multiple: true
      options:
        - 2025-07-16
        - 2025-07-12
    validations:
      required: true
