name: "Training Log"
description: "Register a daily training log in JSON format"
title: "Training Log"
labels: ["training-log"]
body:
  - type: textarea
    id: log
    attributes:
      label: "ユーザー名とログJSON"
      description: "1行目にユーザー名、2行目以降にトレーニングログJSONを貼り付けてください"
    validations:
      required: true
