name: "Training Log"
description: "Register a daily training log in JSON format"
title: "Training Log"
labels: ["training-log"]
body:
  - type: textarea
    id: log
    attributes:
      label: "Training Log JSON"
      description: "Paste the day's training log in JSON format"
    validations:
      required: true
