name: Deploy Vue3 App to Pages

permissions:
  contents: write    # GITHUB_TOKEN にリポジトリへの書き込み権限を付与

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Add or Update Training Log", "Delete Training Log"]
    types:
      - completed

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build production bundle
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
